version: '3.1'
services:
  web:
    image: ducanh30091995/odoo_17_hotel_management:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo_db
    # SỬ DỤNG DỮ LIỆU ĐÃ BAKE-IN TRONG IMAGE
    # Không cần mount folder local giúp hệ thống chạy ổn định chỉ với 1 file .yml

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
