[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$Neb837vXuleKsRaCMKZUyg$jRnBJRS7FgHDGqVeyyVlTyrhq/V2FANu.E459Ixlp4Gcrz6NCVUmhu4qwQsE28TuBYlVBw4Iv7u0aUQHdV84kg

